zooniverse/hamlet

hamlet/celery.py

Google Cloud Storage's transfer utility keeps the full domain name and
path in the gs file path.

Keep full path in gs URLs

---

hamlet/celery.py
hamlet/views.py
hamlet/zooniverse_auth.py

Also stops passing expiration times and refresh token to Panoptes
client, because social_core will handle refreshing the token and the
client doesn't support the correct oauth flow anyway.

Refactor panotpes auth into SocialPanoptes class

---

Dockerfile

Python 3.8 is out and it broke Celery.

Pin Python version to 3.7

---

hamlet/celery.py
templates/ml-subject-assistant.html

Requires #127 
Once PR 127 creates and stores the subject manifest file on Azure, a "Machine Learning Task" request needs to be submitted to the Machine Learning service. This tells the service that, hey, please take a look at this funky fresh new subject manifest file.
This PR submits that request.
- A fourth sub-task has been added to the `ml_subject_assistant_export_to_microsoft()` Celery task.
- This sub-tasks submits a properly formatted POST to the ML service, and receives a "request_id" in return, which is saved to the database.
- This "request_id" can later be passed to the Subject Assistant front end.
New Requirements:
- for the new functionality to work, the following variables now need to be specified in the environment: `SUBJECT_ASSISTANT_ML_SERVICE_CALLER_ID`, …

Make ML Task request to ML Service

---

hamlet/views.py

This PR fixes an issue on the Subject Assistant pages which causes 500 error pages when a Subject Set never had a history of being exported.
- Error occurs when a user visits a Subject Assistant Project page (e.g. `http://localhost:8080/subject-assistant/10560/`) with a Subject Set that hasn't been exported (i.e. no export data in the database)
- Error located at `hamlet/views.py`, in function `ml_subject_assistant_list()`.
- Solution is a simple existence check.
Tested on localhost using a Zooniverse user with a Project with un-exported Subject Sets. Subject Assistant page continues to work for users with exported Subject Sets. 
Ready for review!

Fix Subject Assistant's 'index out of bounds' error

---

kubernetes/deployment.tmpl

This fixes an issue where the deployed Kubernetes pods weren't reading the Environment Variables (for the Subject Assistant) from the Secrets. Issue was that I didn't realise that I had to _manually map_ the Subject Assistant's Secrets to the pod's env variables.
Lessons learned: if you want a Environmental variable (Secret) in your Kubernetes pod...
1. you need to make sure your app code reads the Env variable from process.env.MY_DB_PASSWORD or whatever.
2. make sure you set your MY_DB_PASSWORD values in your Kubernetes Secrets.
3. map the values from the Secrets to the Environment variables in your Kubernetes deployment.tmpl file. 
4. and if you change the value of the Secrets (e.g. via kubectl edit secrets XYZ), remember to restart the Kubernetes pod
(In this PR's case, merging this PR …

Fix ML Subject Assistant's missing environment variables

---

hamlet/settings.py
kubernetes/deployment.tmpl

Closes #211 
Additional details: #210 
This PR attempts to add an Nginx server to the Hamlet deployment, so the Hamlet app can serve static files. This PR only affects **production deployment** and has no effect on staging/development modes.
Notes:
- Static files at the `/static` URL should be visible to all users.
- e.g.: https://hamlet-staging.zooniverse.org/static/zooniverse-logo-white.png
- On the server's file system, the static files would be found in the `(project's BASE_DIR)/hamlet/static` folder, if I'm correct. (🤔)
Do not merge. Awaiting review and advice from @camallen 
Additional comments on what I _think_ I'm doing to follow.

Add Nginx and static file support

---

kubernetes/deployment.tmpl

1. fix the static assets path for serving via nginx
2. ensure we pass the HOST to the upstream proxy DJANGO app
3. update the the liveness probes to correctly test the app

Fix nginx deployment configs for static assets

---

kubernetes/deployment.tmpl

avoid OOM killer in the k8s container, increase the RAM to 500Mi

update celery ram limits

---

kubernetes/deployment.tmpl

avoid the host disk for any disk IO, use the tmp disks

switch to temp scratch disk for static assets

---

hamlet/settings.py

use an SSL connection by default for the non-dev dbs and fallback to non-ssl mode for local deb / CI envs
> first try an SSL connection; if that fails, try a non-SSL connection
https://www.postgresql.org/docs/11/libpq-connect.html

use SSL connection mode in non-dev envs

---

docker-compose.yml
hamlet/settings.py
kubernetes/deployment.tmpl

Match the server requirements for SSL mode but still allow the dev machines to boot via docker-compose

Allow deploy envs DB connections to be secure

---

kubernetes/deployment.tmpl
start_server.sh

ensure we have enough workers to handle request loads. Avoid pod restarting due to busy worker

Improve app perf and k8s timeouts

---

hamlet/celery.py

allow automatic runtime service detection of Zooniverse camera traps API via k8s service ENV vars and use this if available. If not then fallback to the externally hosted service via k8s secrets (MS are deprecating this API, EOL is JAN 2022)

autodected and use zoo hosted camera traps API service

---

kubernetes/deployment.tmpl

moved from https://github.com/zooniverse/static/pull/260 to this repo and adds `hamlet.zooniverse.org` to the "staging" service container. Note staging service talks to production APIs

add k8s ingress

---

Jenkinsfile

no need to track the branch name via image tags, just the git sha ref is used for deployment

simplify the docker build tags in jenkinsfile

---

hamlet/zooniverse_auth.py

use the main www.zooniverse.org domain to allow for single sign on (SSO)

switch to SSO domain for oauth

---

kubernetes/deployment-staging.tmpl
start_server.sh

Add commit_id.txt to the static assets and ensure we serve that off the root via a custom nginx location directive

allow system to report the deployed state of the service

---

hamlet/kade_service.py

allow the kade service URL to be set via and env var and fall back to non tls scheme url from k8s service envs

use internal non tls scheme for internal k8s traffic

---

.github/workflows/deploy_production.yml

prod deploy is tag based so reflect this in the GH actions workflow yaml

allow deploys via production-release tag

---

poetry.lock

This updates closes two dependabot security alerts in [cryptography](https://github.com/pyca/cryptography).

[Security] Bump cryptography from 41.0.0 to 41.0.3

---

README.md

This PR updates Hamlet's README with (1) a short introduction, and, more importantly, (2) a new Troubleshooting section (under Development), that follows recent debug attempts.
With this information, devs should now be able to get Hamlet running on local development once again. Fingers crossed!
Closes #479 as well

README: add intro, and add dev troubleshooting section

---

hamlet/ms_ml_exports.py

This updates CAMERA_TRAPS_API_SERVICE_HOST_PATH to target the current host path if no env variable is set. (It usually ain't.)

Change default target for CAMERA_TRAPS_API_SERVICE_HOST_PATH
