zooniverse/hamlet

Dockerfile
kubernetes/deployment.tmpl

and fix path to celery entrypoint

Actually copy app into Docker image

---

exports/models.py
hamlet/celery.py

Refactor export models (DRY)

---

hamlet/settings.py
hamlet/urls.py
templates/registration/login.html

Copies the solution from python-social-auth/social-app-django#55

Require POST for auth and add login form

---

hamlet/settings.py

Expire sessions on close

---

hamlet/celery.py

Retry failed celery jobs where possible

---

hamlet/views.py
hamlet/zooniverse_auth.py

Validate the user's project role

---

hamlet/views.py
hamlet/zooniverse_auth.py

- Catch `TypeError` if user doesn't have a session (closes #96)
- Use `get_access_token()` method to refresh the token if it's expired.
- Refactor `social_auth` and `SocialPanoptes` setup.

Correctly refresh expired tokens

---

Jenkinsfile
kubernetes/deployment.tmpl

- Set Jenkins kubectl context
- Reconfigure persistent volume claims
- Add AWS credentials

Update deployment for Azure

---

hamlet/settings.py

I'm getting a signature error and I'm not actually certain this will fix
it. Ruling this out first though.

Set S3 signature version

---

hamlet/settings.py

This reverts commit db59d794ca41a06e800afcaa467df5f6686be2ef.
This wasn't the issue. There was a problem with the credentials.

Revert "Set S3 signature version"

---

Pipfile
Pipfile.lock

There are breaking changes in Django 3 but there are also some security updates for Django 2.

Limit django 2

---

Pipfile
Pipfile.lock

The Azure packages are a confusing mess and I don't have time to figure
them out right now.

Switch back to azure package and pin to old version

---

README.md

Ensure the readme has the correct instructions to test / run the app

replace pipenv cmds with their scripts

---

kubernetes/deployment-staging.tmpl

linked to the change in #426 but this time with the correct static file paths

use the correct path to static files

---

hamlet/celery.py
hamlet/kade_service.py

used for links in html views on the public internet

use public kade service URL

---

hamlet/kade_service.py

add correct prediction_jobs resource paths to public_url

---

.github/workflows/deploy_production.yml
kubernetes/deployment-production.tmpl

add hamlet production deployment

---

kubernetes/deployment-production.tmpl
kubernetes/deployment-staging.tmpl

follow up on #433 - ensure the k8s yaml is valid

fix indentation levels

---

kubernetes/deployment-production.tmpl

specifcally the redis setup, use the 
1. correct redis service name
2. ensure our redis PVC files system is read write once access, not many as it could be dangerous to redis

Update prod deployment

---

kubernetes/deployment-production.tmpl

ensure we have a uniq ingress name for production

fix prod ingress

---

Dockerfile

Let’s see if this gets builds working again.

Replace netcat with netcat-openbsd

---

.github/workflows/build_branch.yml

Run the Docker build for PR branches, but don't push or deploy.
Closes #451.

Build PR branches

---

templates/index.html
templates/ml-subject-assistant.html
templates/project.html

August 2023 content update with new text from Sarah Huebner.
Closes #448.

Content update
